### ISSUE TITLE
JS Source

### ISSUE THREAD

**Issue by cisnky** [triqui/jQuery-Bejeweled#1]
You've not added the source. Can only see the ReadMe.

**Comment by triqui** [comment]
Yes, the problem is: I can't add the source. I did not find a way to do 
it. Any clue?

Il 10/10/2011 09:10, cisnky ha scritto:

> You've not added the source. Can only see the ReadMe.

**Comment by cisnky** [comment]
If you are on a Mac you can use http://mac.github.com/
